### ISSUE TITLE
EPIC: analysis ready data access/data retrieval from Dashboard

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/covid-api#138]
"Power users" might want to grab data from the dashboard to perform further analysis on. This might be underlying COG's, a jupyter notebook, `.tif` files, or `.csv` files corresponding to time series graphs

**Comment by leothomas** [comment]
Some thoughts on the design of this feature: 

Using the API to find COGs and download them directly from S3 is documented [here](https://github.com/NASA-IMPACT/covid-api/blob/develop/guidelines/api-usage.md). These instructions might be confusing to non-technical users, as they require knowledge of REST APIs, the AWS CLI and downloading file objects from the terminal using `cURL` or `wget` (although I would assume that most people interested in downloading COGs have at least _some_ knowledge of the above topics). 

### WebMap Tiles:
The binary content of the web map tiles generated by the API can be wrapped in a [StreamingResponse](https://fastapi.tiangolo.com/advanced/custom-response/#streamingresponse) object, which will be downloaded by most browsers

### Source COGs: 
The source COG should **not** be downloaded to the user's machine using the same StreamingResponse technique as above, as this would entail loading the entire COG into the lambda's runtime memory. Even using the FileResponse object would require the entire COG to be copied over to the Lambda's runtime environment

I suggest returning an [S3 presigned url](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-presigned-urls.html) as a [RedictResponse](https://fastapi.tiangolo.com/advanced/custom-response/#redirectresponse) - which should also have the same result of downloading the file in the user's browser.

### CSV's for mean/median values (from the AOI feature and `/timelapse` endpoint)
Using the [CSV Middleware](https://github.com/earthrise-media/trace-emissions-api/blob/7640646c17f285bf0a4febab34c6fd4df614bc80/api/app/main.py#L68-L126) from the Trace Emissions API we can easily add an `accept` header that specifies the `text/csv` mimetype as a return type - this will convert the JSON result of the API call into a CSV object which will be returned as a StreamingResponse (and download in most browsers).

**Comment by olafveerman** [comment]
This is currently being dealt with on the frontend. Closing this issue.
