### ISSUE TITLE
Add dataset discoverability

### ISSUE THREAD

**Issue by drewbo** [NASA-IMPACT/covid-api#36]
Re: https://github.com/NASA-IMPACT/covid-dashboard/issues/340

One of the current drawbacks of the API is that it's not possible to see what datasets/COGs are currently available to visualize. We need to make this information discoverable from the API. Users should be able to hit the `/datasets` endpoint and see:
- what "layers" are available (CO2, NO2, Nightlights, etc)
- for each layer:
  - what is the tile URL (including preferred scaling, colormap, and resampling parameters)
  - what are the available dates
  - what are the available locations (if the data is global or not)
  - does that data have a comparison layer available
  - (optional) is the data available for querying via the timelapse feature 

Because the root S3 bucket contains other paths and the data isn't particularly well organized, we'll likely need to hardcode some information or propose a renaming strategy on the S3 bucket (or some combination of both)

cc: @danielfdsilva @olafveerman

**Comment by danielfdsilva** [comment]
It is important to note that for some layers, the information (like dates) may change depending on the location.

**Comment by leothomas** [comment]
A branch is open [here](https://github.com/NASA-IMPACT/covid-api/tree/feature/dataset-discoverability) which implements dynamic domain extraction by dataset and by spotlight (depending on which endpoint is hit: `/dataset` and `/dataset/{spotlight_id}` respectively. 

I'm currently working on unit tests for the branch
